[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm ci"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
nodejs = "18"
